site_name: AOSP Build Include Graph
site_url: https://ilaveniranjith.github.io/
site_author: Ilaveni Ranjith (ranjith.ilaveni@gmail.com)
site_description: Basic notes of AOSP

theme:
  icon:
    logo: fontawesome/solid/diagram-project
  favicon: android.svg #icon.png
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  hide:
    - navigation
    - toc
    - feedback
  

  font:
    text: Noto Serif
    code: Roboto Mono
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: black
      accent: black 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: black
      accent: deep orange
  
  plugins:
   - pdf-with-js
   - search
   - autozip:
       source_zip_dir: download
       source_zip_file_name: my_source.zip
       add_source_zip_to_nav: false
       source_zip_nav_description: download the source for this site as a zip
       download_images: true
       download_image_zip_dir: downloaded_images
       verbose: true
   - glightbox:
       touchNavigation: true
       loop: false
       effect: zoom
       slide_effect: slide
       width: 100%
       height: auto
       zoomable: true
       draggable: true
       skip_classes:
       - custom-skip-class-name
       auto_caption: false
       caption_position: bottom



  
extra:
  #footer-note: Made with :octicons-heart-fill-24:{ .mdx-heart } by the Ilaveni Ranjith.
  generator: false
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/IlaveniRanjith
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/IlaveniRanjith?t=RxkThMbzUZcAb6Wxc_VSTg&s=09
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/ranjith-ilaveni-8386a6179
      

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy: 2023 <a href="https://github.com/IlaveniRanjith"  target="_blank" rel="noopener">Ilaveni Ranjith</a>

# copyright: > # should remain a link to the original theme
# &copy; 2021 Code Inside Out<br>
# <a href="https://github.com/vuquangtrong/mkdocs-material-blog">Blog
# Theme</a> /
# <a href="